// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 9.3
// Project name: coffee_timer

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_ScreenContainer = NULL;
lv_obj_t * ui_Countdown = NULL;
lv_obj_t * ui_Battery = NULL;
lv_obj_t * ui_BatteryLabel = NULL;
lv_obj_t * ui_Arc1 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_remove_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_ScreenContainer);
    lv_obj_set_width(ui_ScreenContainer, 466);
    lv_obj_set_height(ui_ScreenContainer, 466);
    lv_obj_set_align(ui_ScreenContainer, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_ScreenContainer,
                       LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE |
                       LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE);     /// Flags
    lv_obj_set_style_transform_rotation(ui_ScreenContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_x(ui_ScreenContainer, 233, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_pivot_y(ui_ScreenContainer, 233, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Countdown = lv_label_create(ui_ScreenContainer);
    lv_obj_set_width(ui_Countdown, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Countdown, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Countdown, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Countdown, "00:00");
    lv_obj_set_style_text_font(ui_Countdown, &ui_font_DynaPuff_90, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Battery = lv_bar_create(ui_ScreenContainer);
    lv_bar_set_value(ui_Battery, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Battery, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Battery, 50);
    lv_obj_set_height(ui_Battery, 12);
    lv_obj_set_x(ui_Battery, 0);
    lv_obj_set_y(ui_Battery, 220);
    lv_obj_set_align(ui_Battery, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x0A4700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Battery, lv_color_hex(0x0FFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Battery, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    //Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
    if(lv_obj_get_style_pad_top(ui_Battery, LV_PART_MAIN) > 0) lv_obj_set_style_pad_right(ui_Battery,
                                                                                              lv_obj_get_style_pad_right(ui_Battery, LV_PART_MAIN) + 1, LV_PART_MAIN);
    ui_BatteryLabel = lv_label_create(ui_ScreenContainer);
    lv_obj_set_width(ui_BatteryLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BatteryLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BatteryLabel, 0);
    lv_obj_set_y(ui_BatteryLabel, 205);
    lv_obj_set_align(ui_BatteryLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BatteryLabel, "100%");
    lv_obj_set_style_text_color(ui_BatteryLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BatteryLabel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc1 = lv_arc_create(ui_ScreenContainer);
    lv_obj_set_width(ui_Arc1, 450);
    lv_obj_set_height(ui_Arc1, 450);
    lv_obj_set_x(ui_Arc1, 1);
    lv_obj_set_y(ui_Arc1, 3);
    lv_obj_set_align(ui_Arc1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_Arc1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                       LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE);     /// Flags
    lv_arc_set_value(ui_Arc1, 50);
    lv_obj_set_style_arc_width(ui_Arc1, 25, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_width(ui_Arc1, 25, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_shadow_color(ui_Arc1, lv_color_hex(0x969696), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_Arc1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_Arc1, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_Arc1, 3, LV_PART_KNOB | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_ScreenContainer = NULL;
    ui_Countdown = NULL;
    ui_Battery = NULL;
    ui_BatteryLabel = NULL;
    ui_Arc1 = NULL;

}
